runtime: python
api_version: 3
threadsafe: true

libraries:
- name: ssl
  version: latest

#instance_class: F2
env: flex
runtime_config:
  python_version: 3
manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  DEBUG: 'True'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
